dist: xenial
services: docker
#addons:
#  homebrew:
#    casks:
#    - virtualbox
#
#script:
#
#  # Swarm
##  - base=https://github.com/docker/machine/releases/download/v0.16.0 &&
##    curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine &&
##    sudo install /tmp/docker-machine /usr/local/bin/docker-machine
##  - sudo apt-get update
##  - brew cask install virtualbox
#  - brew install docker-machine
#  - export ES_MASTER_NODES=1
#  - export MACHINE=virtualbox
#  -  ./machine.sh init
#  - sleep 180
#  - echo '198.20.69.74' | nc $(docker-machine ip manager-1) 5000
#  - sleep 120
#  - curl -s -XPOST -u "elastic:changeme" 'http://$(docker-machine ip manager-1):9200/_refresh'
#  - curl -s -u "elastic:changeme" 'http://$(docker-machine ip manager-1):9200/_count?q=198.20.69.74' | egrep '^{"count":1,'
#  - curl -s -u "elastic:changeme" 'http://$(docker-machine ip manager-1):9200/_search?q=198.20.69.74&pretty'
#  - docker stack services elastic
#  - docker service logs elastic_elasticsearch
#  - docker service logs elastic_kibana
#  - docker service logs elastic_logstash
#  - docker service logs elastic_filebeat


script:

  # Swarm
  - sudo apt-get update
  - wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
  - wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
  - wget https://download.virtualbox.org/virtualbox/6.0.6/virtualbox-6.0_6.0.6-130049~Ubuntu~xenial_amd64.deb
  - sudo apt-get install -y ./virtualbox-6.0_6.0.6-130049~Ubuntu~xenial_amd64.deb
  - sudo systemctl start virtualbox
  - base=https://github.com/docker/machine/releases/download/v0.16.0 &&
    curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine &&
    sudo install /tmp/docker-machine /usr/local/bin/docker-machine
  - export ES_MASTER_NODES=1
  - export MACHINE=virtualbox
  -  ./machine.sh init
  - sleep 180
  - echo '198.20.69.74' | nc $(docker-machine ip manager-1) 5000
  - sleep 120
  - curl -s -XPOST -u "elastic:changeme" 'http://$(docker-machine ip manager-1):9200/_refresh'
  - curl -s -u "elastic:changeme" 'http://$(docker-machine ip manager-1):9200/_count?q=198.20.69.74' | egrep '^{"count":1,'
  - curl -s -u "elastic:changeme" 'http://$(docker-machine ip manager-1):9200/_search?q=198.20.69.74&pretty'
  - docker stack services elastic
  - docker service logs elastic_elasticsearch
  - docker service logs elastic_kibana
  - docker service logs elastic_logstash
  - docker service logs elastic_filebeat